---
- name: Creating and Activating  pvlan
  connection: network_cli
  hosts: all
  gather_facts: no
  tasks:
    - name: create pvlan 
      cli_command:
        command: pvlan 200 name "corporate PVLAN"
#        command: pvlan 200 admin-state enable 
    - name: enable pvlan
      cli_command:
        command: pvlan 200 admin-state enable
    - name: create secondary isolated pvlan
      cli_command:
        command: pvlan 200 secondary 250 type isolated
    - name: create secondary community pvlan
      cli_command:
        command: pvlan 200 secondary 250 type community 
    - name: tag primary pvlan to port 
      cli_command: 
        command: pvlan 200 member port 1/1/1-2 tagged
    - name: tag isoltaed pvlan to port
      cli_command:
        command: pvlan 250 member port 1/1/3-4 tagged
    - name: tag community pvlan to port
      cli_command:
        command: pvlan 251 member port 1/1/5-6 tagged
      register: pvlan
    - name: debug Creating and Activating  PVLAN
      debug:
        msg: "{{pvlan }}"

